apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:  
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xms1g
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ingest.geoip.downloader.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
          livenessProbe:
            exec:
              command:
                - curl -f http://elasticsearch:9200 || exit 1
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
