apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      
    scrape_configs:
      - job_name: "dapr"
        static_configs:
          - targets: 
              - "host.docker.internal:9091"
              - "host.docker.internal:9092"