apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: vault
    spec:
      containers:
        - args:
            - server
          env:
            - name: VAULT_CLUSTER_ADDR
              value: http://vault:8201
            - name: VAULT_API_ADDR
              value: http://vault:8200
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_LOCAL_CONFIG
              value: |
                {
                  "storage": {
                    "raft": {
                      "path": "/vault/data"
                    }
                  },
                  "listener": [{
                    "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": 1
                    }
                  }],
                  "default_lease_ttl": "168h",
                  "max_lease_ttl": "720h",
                  "ui": true,
                  "cluster_name": "vault-cluster",
                  "cluster_address": "http://vault:8201"
                }
          image: hashicorp/vault:1.15.0
          name: vault
          ports:
            - containerPort: 8200
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /vault/data
              name: vault-data
      restartPolicy: Always
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

