apiVersion: v1
kind: Service
metadata:
  name: lessonservice
spec:
  selector:
    app: lessonservice
  ports:
    - protocol: TCP
      name: "5060"
      port: 5060
      targetPort: 5060
  type: LoadBalancer
  