global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dapr-sidecars'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'dapr-sidecar-activity:9091'
          - 'dapr-sidecar-activity-grpc:9092'
