apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisSentinelMasterName
    value: "mymaster"
  - name: redisSentinelAddresses
    value: "host.docker.internal:6570,host.docker.internal:6571,host.docker.internal:6572"
