version: '3.9'
networks:
  edem-redis-network1:
    driver: bridge

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --port 6379 --appendonly yes
    networks:
      - edem-redis-network1
        
  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    depends_on:
      - redis-master
    ports:
      - "6370:6370"
    command: redis-server --port 6370 --appendonly yes --slaveof redis-master 6379
    networks:
      - edem-redis-network1

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    depends_on:
      - redis-master
    ports:
      - "6375:6375"
    command: redis-server --port 6375 --appendonly yes --slaveof redis-master 6379
    networks:
      - edem-redis-network1

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6570:6570"
    command: >
      sh -c 'echo "port 6570\n
      sentinel monitor mymaster redis-master 6379 2\n
      sentinel down-after-milliseconds mymaster 5000\n
      sentinel failover-timeout mymaster 5000\n
      sentinel parallel-syncs mymaster 1\n
      protected-mode no\n
      sentinel resolve-hostnames yes" > /tmp/sentinel.conf && redis-server /tmp/sentinel.conf --sentinel'
    networks:
      - edem-redis-network1

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6571:6571"
    command: >
      sh -c 'echo "port 6571\n
      sentinel monitor mymaster redis-master 6379 2\n
      sentinel down-after-milliseconds mymaster 5000\n
      sentinel failover-timeout mymaster 5000\n
      sentinel parallel-syncs mymaster 1\n
      protected-mode no\n
      sentinel resolve-hostnames yes" > /tmp/sentinel.conf && redis-server /tmp/sentinel.conf --sentinel'
    networks:
      - edem-redis-network1

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6572:6572"
    command: >
      sh -c 'echo "port 6579\n
      sentinel monitor mymaster redis-master 6379 2\n
      sentinel down-after-milliseconds mymaster 5000\n
      sentinel failover-timeout mymaster 5000\n
      sentinel parallel-syncs mymaster 1\n
      protected-mode no\n
      sentinel resolve-hostnames yes" > /tmp/sentinel.conf && redis-server /tmp/sentinel.conf --sentinel'
    networks:
      - edem-redis-network1