apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redis-slave-1
  name: redis-slave-1
spec:
  type: LoadBalancer
  ports:
    - name: "6370"
      port: 6370
      targetPort: 6370
  selector:
    io.kompose.service: redis-slave-1
