apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redis-slave-1
  name: redis-slave-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-slave-1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: redis-slave-1
    spec:
      containers:
        - args:
            - redis-server
            - --port
            - "6370"
            - --appendonly
            - "yes"
            - --slaveof
            - redis-master
            - "6379"
          image: redis:latest
          name: redis-slave-1
          ports:
            - containerPort: 6370
              protocol: TCP
      restartPolicy: Always
