apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: sentinel-2
  name: sentinel-2
spec:
  type: LoadBalancer
  ports:
    - name: "6571"
      port: 6571
      targetPort: 6571
  selector:
    io.kompose.service: sentinel-2
