apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: sentinel-1
  name: sentinel-1
spec:
  type: LoadBalancer
  ports:
    - name: "6570"
      port: 6570
      targetPort: 6570
  selector:
    io.kompose.service: sentinel-1
