apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-appsettings-config
data:
  appsettings.Development.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      }
    }
  appsettings.json: | 
    {
      "Logging": {
        "Serilog": {
          "MinimumLevel": {
            "Default": "Information",
            "Override": {
              "Microsoft": "Information",
              "System": "Warning"
            }
          }
        },
        "LoggerType": "Serilog"
      },
      "AllowedHosts": "*",
      "ServiceName": "EDemApp.Gateway-Ocelot",
      "Consul": {
        "ServiceName": "Gateway-Ocelot",
        "ServiceId" : "b0b28634e66a439d8e62e92ae4e12146",
        "Vault": {
          "token": "hvs.Ivh7vru7LjOsUZFSdUPdnNii",
          "Address": "http://vault:8200"
        }
      }
    }

