apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      name: "5081"
      port: 5081
      targetPort: 5081
  type: LoadBalancer
  